[package]
name = "dotfiles-cli"
version = "0.1.0"
edition = "2024"
rust-version = "1.91"
description = "Cross-platform dotfiles management engine"
license = "MIT"
publish = false

[[bin]]
name = "dotfiles"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
enable-ansi-support = "0.2"
git2 = "0.20.4"
rayon = "1.10"
which = "8.0.0"

[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"

[lints.clippy]
pedantic = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cast_possible_truncation = "allow"
missing_errors_doc = "allow"
module_name_repetitions = "allow"
cargo = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"
unwrap_used = "warn"
expect_used = "warn"
todo = "warn"
unimplemented = "warn"
indexing_slicing = "warn"

[lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
